---
title: "supplement"
output: html_document
date: "2025-04-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(Hmisc)

# data
source("load.R")
generalization_words = read_csv("artifacts/NPJ2025/data/holdout_words.csv")



words = read_csv("artifacts/NPJ2025/data/kidwords.csv", col_names = "word")

samples = read_csv("data/samples.csv", col_names = F)
holdout = read_csv("data/holdouts.csv", col_names = F)$X1

generalization_words = words %>% 
  mutate(in_holdout = holdout) %>% 
  filter(in_holdout == 1) %>% 
  select(word) %>% 
  write_csv("artifacts/NPJ2025/data/holdout_words.csv", col_names = F)


training_sets = samples %>% 
  mutate(word = words$word) %>% 
  pivot_longer(cols = -word, names_to = "model_id", values_to = "present_or_absent") %>% 
  filter(present_or_absent == 1) %>% 
  mutate(model_id = str_remove(model_id, "X"),
         model_id = as.numeric(model_id)) %>% 
  arrange(model_id) %>% 
  select(-present_or_absent)

write_csv(training_sets, file = "artifacts/NPJ2025/data/training_sets.csv")

```


# Words included in experimentation
## Words in training sets
The identities of words include across all models. Select a value for `target_model_id` to inspect the words associated with it.

```{r}
target_model_id = 1

training_sets = read_csv("data/training_sets.csv")

training_sets %>% 
  filter(model_id == target_model_id) %>% 
  view()


```

## Words in generalization set
```{r}
generalization_words = read_csv("data/holdout_words.csv", col_names = "word")

generalization_words %>% 
  view()


```

